### ISSUE TITLE
Postgresql 10 and relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by jfrez** [dlr-eoc/pgh3#1]
Hi, i keep getting the -fPIC error for shared libraries, it seems there is a problem with the makefile and postgresql 10. I tried running the command manually  adding the -fPIC but i get the same error.

gcc -I/usr/local/include/ -L/usr/local/lib/ -fPIC  -DEXTVERSION='"0.2.0"' -shared  -fPIC -shared -o pgh3.so src/hierarchy.o src/neighbor.o src/pgh3.o src/index.o src/util.o src/region.o src/misc.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed  -lh3 
/usr/bin/ld: /usr/local/lib//libh3.a(algos.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

pg_config cflags aready includes the -fPIC parameter, so i have no idea how to fix this.

pg_config --cflags
-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer

**Comment by nmandery** [comment]
Hi, 

did you add the `-DBUILD_SHARED_LIBS=1` switch to cmake when building the uber/h3 library? So far I did not get the compiler to link a static libh3 to this extension - the solution so far is to compile h3 as a shared library. 

Also see the installation instructions in the README.md of this repository.

**Comment by dfellis** [comment]
While the answer to this issue has already been given, there's a relevant side topic here on being able to statically link H3 into the pgh3 extension.

@nmandery I'm pretty sure I know the solution to be able to compile the H3 library in statically. In the H3 library if you compile it with `cmake . -DCMAKE_C_FLAGS=-fPIC` the resulting `h3/lib/libh3.a` file will then statically link correctly. (This works in [h3-node](https://github.com/dfellis/h3-node), at least.)

**Comment by jfrez** [comment]
Thanks @nmandery, I removed the previous installation of h3 and its working perfectly.

**Comment by nmandery** [comment]
@jfrez Good to hear it works for you now.

@dfellis Thank you for the hint. I just gave it a try and it indeed builds a statically linked extension. I will add this to the documentation.

**Comment by vrubiolo** [comment]
Hi there, just finding this issue today and wanted to send some thanks for the [good documentation](https://github.com/dlr-eoc/pgh3#installation). 

I was hitting a similar build error for an [Automotive Grade Linux binding](https://docs.automotivelinux.org/docs/en/master/apis_services/reference/af-binder/afb-overview.html) which uses h3

The key was to pass the `-fPIC` flag to the static build of h3 to allow it to link against the shareg AGL binding. 

Thanks much!
