### ISSUE TITLE
CMakeLists.txt missing

### ISSUE THREAD

**Issue by tarnh** [dlr-eoc/pgh3#4]
I could not find any CMakeLists.txt in the sources. Has it been removed?

**Comment by nmandery** [comment]
This extension uses just `make` to build itself partially using the extension building makefiles provided by PoatgreSQL itself. 

I think you saw `cmake` being mentioned in the documentation README. That section documents how to build [h3](https://github.com/uber/h3) as a shared library to later be able to build this database extension. So the relevant `cmake` `CMakeLists.txt` is in H3's repository.
