### ISSUE TITLE
ERRCODE_NUMERIC_VALUE_OUT_OF_RANGE 

### ISSUE THREAD

**Issue by jfrez** [dlr-eoc/pgh3#5]
Hi, there is any way to make a polyfill for large areas?. For some reason this error keeps poping:

"Integer overflow detected when estimating the number of hexagons for a polyfill at resolution"

**Comment by nmandery** [comment]
H3 internally uses a integer to determinate how many hexagons are needed to polyfill a polygon. pgh3 tries to detect when this integer overflows and then exits with the described error.

I am afraid there is not so much to do other then to work around this issue by running polyfill on parts of the polygon and combing the results afterwards. Have a look [this blogpost](http://blog.cleverelephant.ca/2018/06/polygon-splitting.html) for a method to divide a polygon into more-or-less equally sized parts. The additional benefit are greatly reduced memory requirements as the polygons are far smaller and also more roundish in shape - so less h3 indices outside the polygon have to be checked for intersection. This should also speed things up a bit. All described in the blogpost can be performed in a single SQL query.

Hope this helps for your issue.

**Comment by jfrez** [comment]
thanks!
Atte
Jonathan Frez

**Comment by jfrez** [comment]
hi!
I made a workaround using plpgsql recursive function to go down from the biggest h3 that covers a polygon to the required level using h3_to_children, Im going to leave it here if anyone need it:

`
CREATE OR REPLACE FUNCTION _h3_polyfill_loop ( poly text,res integer )  RETURNS SETOF text AS $$
DECLARE
geoms RECORD;
BEGIN 
		  IF h3_get_resolution(poly) < res THEN
					for geoms in 
						select h3_to_children(poly,h3_get_resolution(poly)+1) as h3
						LOOP
						RAISE NOTICE ' res: %', h3_get_resolution(geoms.h3);
							return QUERY select _h3_polyfill_loop(geoms.h3,res);
						END LOOP;
			 ELSE
			 			RAISE NOTICE ' res: %', h3_get_resolution(poly);
						return QUERY select h3_to_children(poly ,h3_get_resolution(poly));
			END IF;
END $$ LANGUAGE 'plpgsql';


CREATE OR REPLACE FUNCTION h3_polyfill2 ( poly GEOMETRY,res integer )  RETURNS SETOF text AS $$
DECLARE
geoms RECORD;
num INT;
currres INT;
BEGIN 
currres := 0;
num :=7;
  WHILE num = 7 LOOP
	currres := currres +1;
   select h3_polyfill_estimate(poly ,currres) into num;
	 END LOOP;
<<loopingin>>
for geoms in
    SELECT (h3_polyfill(poly ,currres)) as h3
		LOOP
		IF st_intersects(st_transform(poly,4326),st_setsrid(h3_h3index_to_geoboundary(geoms.h3),4326)) THEN
			return query select geom from (select _h3_polyfill_loop(geoms.h3,res) as geom) filled where st_intersects(st_transform(poly,4326),st_setsrid(h3_h3index_to_geoboundary(geom),4326));
		END IF;
   END LOOP;
END $$ LANGUAGE 'plpgsql';
`


It works just like polyfill but slower ( really slow for large areas), I'm using it to make convert from raster layers to h3 indexes.

select h3_polyfill2(geom::geometry,7),h3_get_resolution(h3_polyfill2(geom::geometry,7))

**Comment by jfrez** [comment]
Hi!, im leaving this here:

text h3_poly_fill2(geometry poly ,integer initial ,integer final)

I made a "memory friendly" h3_poly_fill (h3_poly_fill2), it requires the polygon, the starting resolution and the final resolution.  The polygon will be filled using the normal poly_fill, however, it will go down to the final resolution asking h3 children ( h3_to_children)  in each level and finally returning the h3 that intersects(st_intersects) the polygon.

`CREATE OR REPLACE FUNCTION _h3_polyfill_loop ( poly text,res integer )  RETURNS SETOF text AS $$
DECLARE
geoms RECORD;
BEGIN 
		  IF h3_get_resolution(poly) < res THEN
					for geoms in 
						select h3_to_children(poly,h3_get_resolution(poly)+1) as h3
						LOOP
							return QUERY select _h3_polyfill_loop(geoms.h3,res);
						END LOOP;
			 ELSE
						return QUERY select h3_to_children(poly ,h3_get_resolution(poly));
			END IF;
END $$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION h3_polyfill2 ( poly GEOMETRY,ires integer,fres integer )  RETURNS SETOF text AS $$
DECLARE
geoms RECORD;
num INT;
BEGIN 
for geoms in
    SELECT h3_polyfill(poly ,ires) as h3
		LOOP
			return query select geom from (select _h3_polyfill_loop(geoms.h3,fres) as geom) filled where st_intersects(st_transform(poly,4326),st_setsrid(h3_h3index_to_geoboundary(geom),4326));
   END LOOP;
END $$ LANGUAGE 'plpgsql';

`

**Comment by jfrez** [comment]
btw, there is a loss in the gap between the polygon exterior and the initial poly_fill, you should use st_buffer in order to generate the h3 that covers completely your area.

**Comment by nmandery** [comment]
Thank you. The gap is caused by the polyfill in the intermediate resolution. Polyfill will only return hexagons whose center intersects with the polygon, so the gap will be up to the "diameter" of the intermediate resolution.
