### ISSUE TITLE
pg_upgradecluster from 11 to 12 -k: H3index fields with bad values

### ISSUE THREAD

**Issue by ArnaudSwail** [dlr-eoc/pgh3#6]
We've noticed that H3Index values are not kept in H3Index type fields when upgrading from PG-11 to PG-12 with -m upgrade -k options. Digging into H3Index type definition, typbyval is set to false in pg 11 and set to true in pg 12.

**Comment by nmandery** [comment]
This extension does not define its own type to store h3index values - instead it uses the `text` type to for the hex-string representation of the indexes.

Could it be you are using [this h3 extension](https://github.com/bytesandbrains/h3-pg) - seems there has been a change related to your observation: https://github.com/bytesandbrains/h3-pg/blob/dd83e80a85cf1f02a836e51e4a774f21ecb27143/h3/sql/updates/h3--3.6.1--3.6.2.sql#L28

**Comment by ArnaudSwail** [comment]
My bad, you're right! I messed up between your extension and theirs!

**Comment by nmandery** [comment]
No worries :wink:
